import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/global.css"
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider as NextThemesProvider, ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <NextThemesProvider attribute="class" defaultTheme="dark">
            <Navbar />
            {children}
          </NextThemesProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
